pipeline {
    agent any

    stages {
    stage('Checkout Code') {
        steps {
            echo 'scm git'
            git branch: 'main', url: 'https://github.com/tecnomc/Project01.git'
        }
    }
    
    
    stage('Compile and Test') {
      steps {
        sh 'ls -ltr'
        // build the project and create a JAR file
        sh 'cd java-cicd-project && mvn compile && mvn test'
      }
    }


    stage('sonar') {
    steps {
        echo 'scanning project'
        sh 'ls -ltr'
        sh '''cd java-cicd-project && mvn sonar:sonar \\
              -Dsonar.host.url=http://localhost:9000 \\
              -Dsonar.login=squ_3c0437cc994fbee5d77d2caf803e4a9e0ebd5775'''
    }
}




stage('Dependency Check') {
    steps {
        withCredentials([string(credentialsId: 'nvd-api-key', variable: 'NVD_API_KEY')]) {
            sh '''
              /opt/dependency-check/bin/dependency-check.sh \
              --project "java-cicd-project" \
              --scan java-cicd-project \
              --format HTML \
              --data $WORKSPACE/odc-data \
              --out dependency-check-report \
              --nvdApiKey "$NVD_API_KEY" \
              --nvdApiDelay 2000
            '''
        }
    }
}



    stage('Publish Report') {
        steps {
            publishHTML([
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'dependency-check-report',
                reportFiles: 'dependency-check-report.html',
                reportName: 'OWASP Dependency-Check Report'
            ])
        }
    }


    stage('Building the code') {
      steps {
        sh 'ls -ltr'
        // build the project and create a JAR file
        sh 'cd java-cicd-project && mvn clean package'
      }
    }

    stage('Build docker image'){
    steps{
        script{
            echo 'docker image build'
  sh 'cd java-cicd-project && docker build -t shilpa1819/project01:${BUILD_NUMBER} .'
        }
    }
}
		
     stage('docker image scan'){
     steps{
         sh "trivy image shilpa1819/project01:${BUILD_NUMBER}"
     }
 }		


stage('Push image to Hub'){
    steps{
        script{
            withCredentials([string(credentialsId: 'dockerhub', variable: 'dockerhub')]) {
            sh 'docker login -u dockerhub -p ${dockerhub}'

      }
            sh 'docker push shilpa1819/project01:${BUILD_NUMBER}'
        }
    }
}


stage('Deploying image to docker container'){
    steps{
        script{
       
            sh 'docker run -itd --name java-app -p 8000:8080 shilpa/java:${BUILD_NUMBER}'
        }
    }
}

  }
}
