pipeline {
    agent any

    stages {
    stage('Checkout Code') {
        steps {
            echo 'scm git'
            git branch: 'main', url: 'https://github.com/tecnomc/Project01.git'
        }
    }
    
    
    stage('Compile and Test') {
      steps {
        sh 'ls -ltr'
        // build the project and create a JAR file
        sh 'cd java-cicd-project && mvn compile && mvn test'
      }
    }


    stage('sonar') {
    steps {
        echo 'scanning project'
         sh 'ls -ltr'
         sh '''cd java-cicd-project && mvn sonar:sonar \\
              -Dsonar.host.url=http://52.55.116.131:9000 \\
              -Dsonar.login=sqa_7d054363f0248784471baf1ea132f0d987bbac6e'''
        }
    }

   stage('Security Scan - Trivy') {
      steps {
        sh '''
        trivy fs --exit-code 1 --severity HIGH,CRITICAL .
        '''
    }
}

    stage('Building the code') {
      steps {
        sh 'ls -ltr'
        // build the project and create a JAR file
        sh 'cd java-cicd-project && mvn clean package'
      }
    }

    stage('Build docker image'){
    steps{
        script{
            echo 'docker image build'
  sh 'cd java-cicd-project && docker build -t shilpa1819/project01:${BUILD_NUMBER} .'
        }
    }
}
		
     stage('docker image scan'){
     steps{
         sh "trivy image shilpa1819/project01:${BUILD_NUMBER}"
     }
 }		


stage('Push image to Hub'){
    steps{
        script{
            withCredentials([string(credentialsId: 'dockerhub', variable: 'dockerhub')]) {
            sh 'docker login -u dockerhub -p ${dockerhub}'

      }
            sh 'docker push shilpa1819/project01:${BUILD_NUMBER}'
        }
    }
}


stage('Deploying image to docker container'){
    steps{
        script{
       
            sh 'docker run -itd --name java-app -p 8000:8080 shilpa/java:${BUILD_NUMBER}'
        }
    }
}

  }
}
